sudo: required
dist: trusty
addons:
   apt:
      sources:
         - google-chrome
      packages:
         - google-chrome-stable

language: node_js
node_js:
  - "node"

script:
  - google-chrome --version
  - npm run test

